Fix JET errors regarding the global `cluster_manager` being defined/undefined
```
┌  @ Distributed /workpath/Distributed.jl/src/process_messages.jl:319
│ `Distributed.cluster_manager` may be undefined: Distributed.cluster_manager
└────────────────────
┌  @ Distributed /workpath/Distributed.jl/src/process_messages.jl:332
│ `Distributed.cluster_manager` may be undefined: Distributed.cluster_manager
└────────────────────
```

We know that the global `cluster_manager` is defined, because it was defined in
the `init_worker(...)` function.

This commit fixes the JET error.

(cherry picked from commit 94de3a2af954453efb6642a4c86f59c9b1f511c0)